name: zmart_websocket
version: "1.0.0"
description: "ZmartBot WebSocket Service - Real-time data streaming and communication"
type: backend
port: 8009
status: active
host: 127.0.0.1
startup_command: "python3 websocket_server.py --port 8009"
stop_command: "pkill -f websocket_server"
dependencies:
  - zmart-api
  - zmart-analytics
  - zmart-notification
health_endpoint: "/health"
ready_endpoint: "/ready"
metrics_endpoint: "/metrics"
created_at: "2025-08-24T21:58:33"
updated_at: "2025-08-25T01:10:42"
