endpoints:
  health: http://127.0.0.1:8007/health
  metrics: http://127.0.0.1:8007/metrics
  ready: http://127.0.0.1:8007/ready
lifecycle:
  health_check: curl -f http://127.0.0.1:8007/health
  start_command: null
  stop_command: pkill -f zmart_analytics
metadata:
  description: Service zmart_analytics
  owner: zmartbot
  version: 1.0.0
service:
  level: 3
  name: zmart_analytics
  passport: ZMBT-ENG-20250831-DBC22A
  port: 8007
  status: ACTIVE
  type: backend
