endpoints:
  health: http://127.0.0.1:8101/health
  metrics: http://127.0.0.1:8101/metrics
  ready: http://127.0.0.1:8101/ready
lifecycle:
  health_check: curl -f http://127.0.0.1:8101/health
  start_command: null
  stop_command: pkill -f enhanced-mdc-monitor
metadata:
  description: Service enhanced-mdc-monitor
  owner: zmartbot
  version: 1.0.0
service:
  level: 3
  name: enhanced-mdc-monitor
  passport: ZMBT-SRV-20250831-32D03B
  port: 8101
  status: ACTIVE
  type: backend
