---
# ⚽ Pele Alerts Service - Level 3 Certified
apiVersion: zmartbot/v1
kind: Service
metadata:
  name: pele-alerts
  namespace: zmartbot-alerts
  labels:
    app: pele-alerts
    tier: level3-certified
    category: alert-system
    owner: zmartbot
spec:
  service:
    name: pele-alerts
    port: 8215
    type: backend
    protocol: HTTP
    certification_level: 3
    passport_id: ZMBT-ALT-20250831-950779
    python_file: pele_alerts_server.py
    
  endpoints:
    health: /health
    alerts: /api/alerts
    status: /api/status
    
  runtime:
    startup_timeout: 30s
    health_check_interval: 60s
    restart_policy: always
    
  deployment:
    replicas: 1
    resources:
      cpu: "100m"
      memory: "128Mi"
    env:
      - name: PORT
        value: "8215"
      - name: LOG_LEVEL
        value: "INFO"
        
  monitoring:
    enabled: true
    metrics_port: 9215
    alerts:
      - name: service-down
        condition: "up == 0"
        severity: critical
      - name: high-latency
        condition: "response_time > 1000"
        severity: warning

  security:
    network_policies:
      - allow_from: ["zmartbot-core", "zmartbot-orchestration"]
      - deny_all: false
    secrets:
      - name: alerts-config
        type: Opaque

  integration:
    dependencies:
      - zmartapi-server:8000
      - database-service:8900
    provides:
      - pele-level-alerts
      - legendary-alerts
      
  backup:
    enabled: true
    retention_days: 30
    schedule: "0 2 * * *"

status:
  phase: Running
  certification:
    level: 3
    issued_date: "2025-08-31"
    expiry_date: "2026-08-31"
    authority: zmartbot-system