#!/bin/bash

# ZmartBot Main API Server Startup Script
# Auto-generated by Claude Doctor

echo "🚀 Starting ZmartBot Main API Server..."

# Navigate to the correct directory
cd /Users/dansidanutz/Desktop/ZmartBot/zmart-api

# Activate virtual environment if it exists
if [ -d "/Users/dansidanutz/Desktop/ZmartBot/.venv" ]; then
    echo "✅ Activating virtual environment..."
    source /Users/dansidanutz/Desktop/ZmartBot/.venv/bin/activate
fi

# Check if port 8000 is already in use
if lsof -Pi :8000 -sTCP:LISTEN -t >/dev/null ; then
    echo "⚠️  Port 8000 is already in use. Killing existing process..."
    kill -9 $(lsof -Pi :8000 -sTCP:LISTEN -t)
    sleep 2
fi

# Set environment variables
export ENVIRONMENT=development
export DEBUG=True
export HOST=0.0.0.0
export PORT=8000

# Create logs directory if it doesn't exist
mkdir -p logs

# Start the main API server
echo "🔧 Starting FastAPI server on port 8000..."
if [ -f "src/services/ZmartBotAPIGateway.ts" ]; then
    echo "⚠️  TypeScript file detected. Converting to Python..."
fi

# Check for main Python files
if [ -f "main.py" ]; then
    echo "📦 Starting main.py..."
    uvicorn main:app --host 0.0.0.0 --port 8000 --reload --log-config=log_config.yaml 2>&1 | tee -a logs/main_api.log &
elif [ -f "run_dev.py" ]; then
    echo "📦 Starting run_dev.py..."
    python3 run_dev.py 2>&1 | tee -a logs/main_api.log &
elif [ -f "simple_server.py" ]; then
    echo "📦 Starting simple_server.py..."
    python3 simple_server.py 2>&1 | tee -a logs/main_api.log &
else
    echo "❌ No main API file found. Creating minimal FastAPI server..."
    cat > main.py << 'EOF'
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
import uvicorn
from datetime import datetime

app = FastAPI(title="ZmartBot API", version="1.0.0")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

@app.get("/")
async def root():
    return {
        "message": "ZmartBot API is running",
        "status": "healthy",
        "timestamp": datetime.now().isoformat()
    }

@app.get("/health")
async def health_check():
    return {
        "status": "healthy",
        "service": "ZmartBot Main API",
        "timestamp": datetime.now().isoformat()
    }

if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=8000, reload=True)
EOF
    python3 main.py 2>&1 | tee -a logs/main_api.log &
fi

# Save the PID
echo $! > logs/main_api.pid

echo "✅ Main API Server started with PID: $(cat logs/main_api.pid)"
echo "📊 Access the API at: http://localhost:8000"
echo "📝 Logs available at: logs/main_api.log"