#!/bin/bash

# Context Cleanup Script for ZmartBot
# Removes auto-generated pollution and optimizes context system

echo "🧹 ZmartBot Context Cleanup"

# 1. Stop background MDC agent
echo "1. Stopping background MDC agent..."
pkill -f "background_mdc_agent.py" 2>/dev/null || true
pkill -f "mdc_generator.py" 2>/dev/null || true

# 2. Clean up polluted MDC files
echo "2. Cleaning polluted MDC files..."
find .cursor/rules -name "*.mdc" -exec sed -i '' '/^\*\*Generated by MDCAgent/d' {} \; 2>/dev/null || true

# 3. Remove context cache to force rebuild
echo "3. Clearing context cache..."
rm -f .claude/context_cache.json
echo '{"file_hashes": {}, "relevance_scores": {}, "last_full_update": "", "domain_contexts": {}}' > .claude/context_cache.json

# 4. Replace current CLAUDE.md with optimized version
echo "4. Installing optimized CLAUDE.md..."
if [ -f "CLAUDE_OPTIMIZED.md" ]; then
    cp CLAUDE.md CLAUDE_BACKUP.md 2>/dev/null || true
    cp CLAUDE_OPTIMIZED.md CLAUDE.md
    echo "✅ CLAUDE.md optimized (backup created)"
else
    echo "⚠️ CLAUDE_OPTIMIZED.md not found"
fi

# 5. Disable auto-update processes
echo "5. Disabling auto-update processes..."
if [ -f "zmart-api/background_mdc_agent.py" ]; then
    mv zmart-api/background_mdc_agent.py zmart-api/background_mdc_agent.py.disabled 2>/dev/null || true
fi

# 6. Clean up duplicate/redundant context files
echo "6. Cleaning redundant context files..."
# Remove empty or minimal context files
find .claude/contexts -name "*.md" -size -100c -delete 2>/dev/null || true

# 7. Performance report
echo ""
echo "📊 Cleanup Results:"
echo "CLAUDE.md size: $(wc -c < CLAUDE.md) characters"
echo "Context files: $(find .claude/contexts -name "*.md" | wc -l) files"
echo "MDC files: $(find .cursor/rules -name "*.mdc" | wc -l) files"
echo "Total .claude size: $(du -sh .claude/ | cut -f1)"

echo ""
echo "✅ Context cleanup completed!"
echo "🎯 Your Claude Code experience should now be faster and cleaner"