apiVersion: v1
kind: Namespace
metadata:
  name: zmartbot

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: zmartbot-config
  namespace: zmartbot
data:
  ENVIRONMENT: "production"
  DEBUG: "false"
  
---
apiVersion: v1
kind: Secret
metadata:
  name: zmartbot-secrets
  namespace: zmartbot
type: Opaque
stringData:
  DATABASE_URL: "postgresql://user:pass@postgres:5432/zmartbot"
  REDIS_URL: "redis://:password@redis:6379/0"
  JWT_SECRET_KEY: "your-secret-key"
  CRYPTOMETER_API_KEY: "your-api-key"
  KUCOIN_API_KEY: "your-api-key"
  KUCOIN_SECRET: "your-secret"
  KUCOIN_PASSPHRASE: "your-passphrase"
  OPENAI_API_KEY: "your-api-key"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zmartbot-app
  namespace: zmartbot
spec:
  replicas: 3
  selector:
    matchLabels:
      app: zmartbot
  template:
    metadata:
      labels:
        app: zmartbot
    spec:
      containers:
      - name: zmartbot
        image: zmartbot:latest
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: zmartbot-config
        - secretRef:
            name: zmartbot-secrets
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: zmartbot-service
  namespace: zmartbot
spec:
  selector:
    app: zmartbot
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: zmartbot
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:14-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: zmartbot
        - name: POSTGRES_USER
          value: zmartbot
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: zmartbot-secrets
              key: POSTGRES_PASSWORD
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: postgres-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 10Gi

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: zmartbot
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: zmartbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:7-alpine
        ports:
        - containerPort: 6379
        command: ["redis-server", "--requirepass", "$(REDIS_PASSWORD)"]
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: zmartbot-secrets
              key: REDIS_PASSWORD

---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: zmartbot
spec:
  selector:
    app: redis
  ports:
  - port: 6379
    targetPort: 6379

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: zmartbot-hpa
  namespace: zmartbot
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: zmartbot-app
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80