#!/bin/bash

# MDC Files Regeneration Script
# Regenerates all MDC files that are missing ChatGPT metadata

echo "🚀 Starting MDC Files Regeneration Process..."
echo "=============================================="

# List of services that need MDC regeneration
SERVICES=(
    "zmart-alert-system"
    "zmart-analytics"
    "zmart-backtesting"
    "zmart-data-warehouse"
    "zmart-machine-learning"
    "zmart-notification"
    "zmart-risk-management"
    "zmart-technical-analysis"
    "zmart-websocket"
    "kingfisher-module"
    "api-keys-manager-service"
    "port-manager-service"
    "binance-worker-service"
    "mdc-orchestration-agent"
)

# Counter for progress tracking
TOTAL=${#SERVICES[@]}
CURRENT=0
SUCCESS=0
FAILED=0

echo "📋 Total services to process: $TOTAL"
echo ""

for service in "${SERVICES[@]}"; do
    CURRENT=$((CURRENT + 1))
    echo "🔄 [$CURRENT/$TOTAL] Processing: $service"
    
    # Call the MDC Orchestration Agent to generate MDC
    RESPONSE=$(curl -s -X POST "http://localhost:8615/mdc/generate/$service")
    TASK_ID=$(echo "$RESPONSE" | jq -r '.task_id')
    
    if [ "$TASK_ID" != "null" ] && [ "$TASK_ID" != "" ]; then
        echo "   ✅ Task created: $TASK_ID"
        
        # Wait for completion
        sleep 3
        
        # Check task status
        TASK_STATUS=$(curl -s "http://localhost:8615/tasks/$TASK_ID" | jq -r '.result.success')
        
        if [ "$TASK_STATUS" = "true" ]; then
            echo "   ✅ MDC generated successfully for $service"
            SUCCESS=$((SUCCESS + 1))
        else
            echo "   ❌ Failed to generate MDC for $service"
            FAILED=$((FAILED + 1))
        fi
    else
        echo "   ❌ Failed to create task for $service"
        FAILED=$((FAILED + 1))
    fi
    
    echo ""
done

echo "=============================================="
echo "🎯 REGENERATION COMPLETE"
echo "=============================================="
echo "✅ Successfully regenerated: $SUCCESS"
echo "❌ Failed: $FAILED"
echo "📊 Total processed: $TOTAL"

# Verify which files now have ChatGPT metadata
echo ""
echo "🔍 VERIFYING GENERATION METADATA..."
echo "=============================================="

CHATGPT_GENERATED=0
for service in "${SERVICES[@]}"; do
    if grep -q "Generated by" ".cursor/rules/$service.mdc" 2>/dev/null; then
        echo "✅ $service - Has ChatGPT metadata"
        CHATGPT_GENERATED=$((CHATGPT_GENERATED + 1))
    else
        echo "❌ $service - Missing ChatGPT metadata"
    fi
done

echo ""
echo "📈 FINAL STATISTICS:"
echo "=============================================="
echo "🎯 Total MDC files with ChatGPT metadata: $CHATGPT_GENERATED"
echo "📁 Total MDC files in system: $(find .cursor/rules -name "*.mdc" | wc -l | tr -d ' ')"
echo "📊 Coverage: $((CHATGPT_GENERATED * 100 / $(find .cursor/rules -name "*.mdc" | wc -l | tr -d ' ')))%"

echo ""
echo "🎉 MDC Regeneration Process Complete!"
