#!/bin/bash

# Smart Context Optimizer for ZmartBot
# Optimizes without breaking the MDC Agent system

echo "🎯 Smart Context Optimization (Preserves MDC Agent)"

# 1. Clean only the repetitive metadata pollution, not the updates
echo "1. Cleaning metadata pollution (preserving updates)..."
find .cursor/rules -name "*.mdc" -exec sed -i '' 's/\*\*Generated by MDCAgent[^*]*\*\*//' {} \; 2>/dev/null || true

# 2. Keep context system but optimize file sizes
echo "2. Optimizing context file sizes..."
for context_file in .claude/contexts/*.md; do
    if [ -f "$context_file" ]; then
        # Keep only essential content, remove excessive metadata
        head -100 "$context_file" > "${context_file}.tmp" && mv "${context_file}.tmp" "$context_file" 2>/dev/null || true
    fi
done

# 3. Status report
echo ""
echo "📊 Smart Optimization Results:"
echo "CLAUDE.md size: $(wc -c < CLAUDE.md) characters"
echo "Context files: $(find .claude/contexts -name "*.md" | wc -l) files"
echo "MDC files: $(find .cursor/rules -name "*.mdc" | wc -l) files"
echo "Last update: $(grep "Last Updated" CLAUDE.md | head -1)"

# 4. Verify MDC system is still working
echo ""
echo "🔍 MDC System Status:"
if grep -q "Auto-updated service knowledge" .cursor/rules/MasterOrchestrationAgent.mdc 2>/dev/null; then
    echo "✅ MDC Agent is active and updating services"
else
    echo "⚠️ MDC Agent status unclear"
fi

echo ""
echo "✅ Smart optimization completed - MDC Agent preserved!"
echo "🎯 Your system updates will continue working normally"