name: zmart_machine_learning
version: "1.0.0"
description: "ZmartBot Machine Learning Service - Predictive models and pattern recognition"
type: backend
port: 8014
status: active

# Service Configuration
config:
  environment: production
  debug: false
  host: "127.0.0.1"
  port: 8014

# Health & Readiness
health:
  endpoint: "/health"
  readiness_endpoint: "/ready"
  timeout: 30s
  interval: 10s

# Dependencies
dependencies:
  - name: "zmart-api"
    port: 8000
    required: true
  - name: "master-orchestration-agent"
    port: 8002
    required: true

# API Endpoints
endpoints:
  - path: "/health"
    method: "GET"
    description: "Health check endpoint"
  - path: "/ready"
    method: "GET"
    description: "Readiness check endpoint"
  - path: "/api/v1/ml/predict"
    method: "POST"
    description: "Make predictions"
  - path: "/api/v1/ml/train"
    method: "POST"
    description: "Train models"
  - path: "/api/v1/ml/evaluate"
    method: "POST"
    description: "Evaluate model performance"
  - path: "/api/v1/ml/models"
    method: "GET"
    description: "List available models"

# Machine Learning Features
ml_features:
  - name: "Predictive Models"
    description: "Price prediction and forecasting"
    status: "active"
  - name: "Pattern Recognition"
    description: "Advanced pattern detection"
    status: "active"
  - name: "Model Training"
    description: "Automated model training"
    status: "active"
  - name: "Feature Engineering"
    description: "Advanced feature extraction"
    status: "active"
  - name: "Model Evaluation"
    description: "Comprehensive model assessment"
    status: "active"

# Data Sources
data_sources:
  - name: "Market Data"
    type: "real-time"
    status: "active"
  - name: "Historical Data"
    type: "analytics"
    status: "active"
  - name: "Feature Data"
    type: "processed"
    status: "active"

# Monitoring
monitoring:
  metrics: "/metrics"
  dashboard: "/dashboard"
  alerts: "/alerts"

# Security
security:
  authentication: "required"
  authorization: "role-based"
  encryption: "enabled"

# Performance
performance:
  caching: "enabled"
  optimization: "active"
  scaling: "horizontal"

# Rollback
rollback:
  snapshots: "enabled"
  data_backup: "automatic"
  configuration: "versioned"
