[build]
  # Build command - not needed for static HTML site
  command = ""

  # Publish directory - current directory contains index.html
  publish = "."

  # Base directory - ClaudeAI/Production folder in repository
  base = "ClaudeAI/Production"

[build.environment]
  # Node version for any potential build tools
  NODE_VERSION = "18"

# SPA redirect rules
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Production context settings
[context.production]
  command = ""
  publish = "."

# Deploy preview settings for testing
[context.deploy-preview]
  command = ""
  publish = "."

# Branch deploy settings
[context.branch-deploy]
  command = ""
  publish = "."

# Build processing settings
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true