service_name: test-websocket-service
service_type: backend
version: 1.0.0
owner: zmartbot
description: Test websocket service
port: 8004
passport_id: ZMBT-SRV-20250826-B47240
status: ACTIVE
registered_at: '2025-08-31'
health_url: http://localhost:8004/health
start_cmd: python3 test_websocket_service_server.py --port 8004
stop_cmd: pkill -f 'test_websocket_service_server.py'
dependencies:
- zmart-api
tags:
- backend
- test-websocket-service
lifecycle:
  startup_grace_seconds: 30
  shutdown_timeout_seconds: 15
  health_check_interval: 30
monitoring:
  metrics_endpoint: /metrics
  logs_path: logs/test-websocket-service.log
  dashboard_url: http://localhost:8004/dashboard
security:
  cors_enabled: true
  token_required: false
  scopes:
  - backend
