service_name: cryptometer-service
service_type: backend
version: 1.0.0
owner: zmartbot
description: Cryptometer service - needs ZMBT passport
port: 8093
passport_id: ZMBT-SRV-20250828-0FAF7F
status: ACTIVE
registered_at: '2025-08-31'
health_url: http://localhost:8093/health
start_cmd: python3 cryptometer_service_server.py --port 8093
stop_cmd: pkill -f 'cryptometer_service_server.py'
dependencies:
- zmart-api
tags:
- backend
- cryptometer-service
lifecycle:
  startup_grace_seconds: 30
  shutdown_timeout_seconds: 15
  health_check_interval: 30
monitoring:
  metrics_endpoint: /metrics
  logs_path: logs/cryptometer-service.log
  dashboard_url: http://localhost:8093/dashboard
security:
  cors_enabled: true
  token_required: false
  scopes:
  - backend
