service_name: port-manager-service
service_type: orchestration
version: 1.0.0
owner: zmartbot
description: Dynamic port allocation and management
port: 8610
passport_id: ZMBT-AGT-20250826-EBA047
status: ACTIVE
registered_at: '2025-08-31'
health_url: http://localhost:8610/health
start_cmd: python3 port_manager_service_server.py --port 8610
stop_cmd: pkill -f 'port_manager_service_server.py'
dependencies:
- zmart-api
tags:
- orchestration
- port-manager-service
lifecycle:
  startup_grace_seconds: 30
  shutdown_timeout_seconds: 15
  health_check_interval: 30
monitoring:
  metrics_endpoint: /metrics
  logs_path: logs/port-manager-service.log
  dashboard_url: http://localhost:8610/dashboard
security:
  cors_enabled: true
  token_required: false
  scopes:
  - orchestration
