service_name: zmart-websocket
service_type: backend
port: 8009
description: "ZmartBot WebSocket real-time data service"
status: ACTIVE
passport_id: ZMRT-SRV-20250826-6532E8
registered_at: "2025-08-26"
health_url: "http://localhost:8009/health"
start_cmd: "python3 zmart_websocket.py"
stop_cmd: "pkill -f 'zmart_websocket.py'"
dependencies:
  - zmart-api
  - database
tags:
  - websocket
  - realtime
  - backend
