endpoints:
  health: http://127.0.0.1:8898/health
  metrics: http://127.0.0.1:8898/metrics
  ready: http://127.0.0.1:8898/ready
lifecycle:
  health_check: curl -f http://127.0.0.1:8898/health
  start_command: null
  stop_command: pkill -f RegistryConsolidator
metadata:
  description: Service RegistryConsolidator
  owner: zmartbot
  version: 1.0.0
service:
  level: 2
  name: RegistryConsolidator
  passport: ZMBT-SRV-20250831-93A7A8
  port: 8898
  status: ACTIVE
  type: backend
