service_name: kingfisher-module
service_type: backend
port: 8100
description: "KingFisher liquidation analysis and trading signals service"
status: ACTIVE
passport_id: ZMBT-SRV-20250826-5D5AA0
registered_at: "2025-08-26"
health_url: "http://localhost:8100/health"
start_cmd: "python3 kingfisher_module.py"
stop_cmd: "pkill -f 'kingfisher_module.py'"
dependencies:
  - zmart-api
  - database
tags:
  - trading
  - kingfisher
  - analysis
