# Diana Platform Configuration
# Central configuration for ZmartBot platform services

platform:
  name: "Diana"
  version: "1.0.0"
  environment: "production"
  deployment_date: "2025-08-24"

# Database configuration
database:
  postgres:
    host: "diana-postgres"
    port: 5432
    database: "zmart_core"
    username: "zmart"
    password: "zmart"
    max_connections: 100
    connection_timeout: 30
    pool_size: 20
    ssl_mode: "disable"
    
  redis:
    host: "diana-redis"
    port: 6379
    database: 0
    max_connections: 100
    connection_timeout: 5
    command_timeout: 10

# Messaging configuration
messaging:
  rabbitmq:
    host: "diana-rabbitmq"
    port: 5672
    vhost: "zmart_vhost"
    username: "zmart_user"
    password: "zmart_rabbitmq_password"
    management_port: 15672
    connection_timeout: 30
    heartbeat: 60
    
  exchanges:
    - name: "trading.events"
      type: "topic"
      durable: true
    - name: "platform.events"
      type: "topic"
      durable: true
    - name: "alerts.events"
      type: "fanout"
      durable: true
      
  queues:
    - name: "trading.positions"
      exchange: "trading.events"
      routing_key: "position.*"
      durable: true
    - name: "trading.orders"
      exchange: "trading.events"
      routing_key: "order.*"
      durable: true
    - name: "platform.health"
      exchange: "platform.events"
      routing_key: "health.*"
      durable: true

# Observability configuration
observability:
  tracing:
    jaeger:
      endpoint: "diana-jaeger:14250"
      service_name: "diana-platform"
      sampler_type: "const"
      sampler_param: 1
      
  metrics:
    prometheus:
      endpoint: "diana-prometheus:9090"
      scrape_interval: "15s"
      push_gateway: "diana-prometheus:9091"
      
  logging:
    level: "INFO"
    format: "json"
    output: "stdout"

# Circuit breaker configuration
circuit_breaker:
  failure_threshold: 5
  recovery_timeout: 30
  test_request_volume: 10
  sleep_window: 10
  error_percentage: 50

# Rate limiting configuration
rate_limiting:
  default: 1000
  api_general: 500
  trading_operations: 100
  market_data: 200
  websocket: 50

# Security configuration
security:
  jwt:
    secret: "diana-platform-jwt-secret-2025"
    expiration: 3600
    refresh_expiration: 604800
    algorithm: "HS256"
    
  cors:
    allowed_origins:
      - "http://localhost:3000"
      - "http://localhost:3400"
      - "http://localhost:5173"
    allowed_methods:
      - "GET"
      - "POST"
      - "PUT"
      - "DELETE"
      - "OPTIONS"
    allowed_headers:
      - "Content-Type"
      - "Authorization"
      - "X-Correlation-ID"
      - "X-Request-ID"

# External services configuration
external_services:
  binance:
    base_url: "https://api.binance.com"
    futures_url: "https://fapi.binance.com"
    timeout: 30
    rate_limit: 1200
    
  kucoin:
    base_url: "https://api-futures.kucoin.com"
    timeout: 30
    rate_limit: 600
    
  cryptometer:
    base_url: "https://api.cryptometer.io"
    timeout: 30
    rate_limit: 100

# Service mesh configuration
service_mesh:
  consul:
    host: "diana-consul"
    port: 8500
    health_check_interval: "30s"
    health_check_timeout: "10s"
    
  service_discovery:
    enabled: true
    registration_ttl: "30s"
    health_check_ttl: "10s"

# Performance configuration
performance:
  connection_pools:
    database: 20
    redis: 10
    http_client: 50
    
  timeouts:
    http_request: 30
    database_query: 10
    cache_operation: 5
    
  caching:
    ttl_default: 300
    ttl_market_data: 60
    ttl_user_session: 3600

# Feature flags
feature_flags:
  trading_enabled: true
  paper_trading: true
  live_trading: false
  ai_predictions: true
  risk_management: true
  circuit_breakers: true
  rate_limiting: true
  distributed_tracing: true
  metrics_collection: true