name: zmart_data_warehouse
version: "1.0.0"
description: "ZmartBot Data Warehouse Service - Data storage, analytics, and reporting"
type: backend
port: 8015
status: active

# Service Configuration
config:
  environment: production
  debug: false
  host: "127.0.0.1"
  port: 8015

# Health & Readiness
health:
  endpoint: "/health"
  readiness_endpoint: "/ready"
  timeout: 30s
  interval: 10s

# Dependencies
dependencies:
  - name: "zmart-api"
    port: 8000
    required: true
  - name: "master-orchestration-agent"
    port: 8002
    required: true

# API Endpoints
endpoints:
  - path: "/health"
    method: "GET"
    description: "Health check endpoint"
  - path: "/ready"
    method: "GET"
    description: "Readiness check endpoint"
  - path: "/api/v1/data/query"
    method: "POST"
    description: "Query data warehouse"
  - path: "/api/v1/data/export"
    method: "POST"
    description: "Export data"
  - path: "/api/v1/data/analytics"
    method: "POST"
    description: "Run analytics queries"
  - path: "/api/v1/data/reports"
    method: "GET"
    description: "Generate reports"

# Data Warehouse Features
warehouse_features:
  - name: "Data Storage"
    description: "Comprehensive data storage and management"
    status: "active"
  - name: "Data Analytics"
    description: "Advanced analytics and reporting"
    status: "active"
  - name: "Data Integration"
    description: "Multi-source data integration"
    status: "active"
  - name: "Data Quality"
    description: "Data quality monitoring and validation"
    status: "active"
  - name: "Data Governance"
    description: "Data governance and compliance"
    status: "active"

# Data Sources
data_sources:
  - name: "Market Data"
    type: "real-time"
    status: "active"
  - name: "Trading Data"
    type: "operational"
    status: "active"
  - name: "Analytics Data"
    type: "processed"
    status: "active"

# Monitoring
monitoring:
  metrics: "/metrics"
  dashboard: "/dashboard"
  alerts: "/alerts"

# Security
security:
  authentication: "required"
  authorization: "role-based"
  encryption: "enabled"

# Performance
performance:
  caching: "enabled"
  optimization: "active"
  scaling: "horizontal"

# Rollback
rollback:
  snapshots: "enabled"
  data_backup: "automatic"
  configuration: "versioned"
