service_name: snapshot-service
service_type: backend
port: 8085
description: "System snapshot and backup service"
status: ACTIVE
passport_id: ZMBT-SRV-20250826-0D2B65
registered_at: "2025-08-26"
health_url: "http://localhost:8085/health"
start_cmd: "python3 snapshot_service.py"
stop_cmd: "pkill -f 'snapshot_service.py'"
dependencies:
  - zmart-api
  - database
tags:
  - backup
  - snapshot
  - system
