endpoints:
  health: http://127.0.0.1:8016/health
  metrics: http://127.0.0.1:8016/metrics
  ready: http://127.0.0.1:8016/ready
lifecycle:
  health_check: curl -f http://127.0.0.1:8016/health
  start_command: python3 maradona_alerts_server.py
  stop_command: pkill -f maradona-alerts
metadata:
  description: Maradona Reversal Pattern Alerts
  owner: zmartbot
  version: 1.0.0
service:
  level: 3
  name: maradona-alerts
  passport: ZMBT-ALT-20250831-FA44D3
  port: 8016
  status: ACTIVE
  type: backend
