# Diana Grafana Datasources Configuration
# Auto-provisioning of data sources for ZmartBot observability

apiVersion: 1

deleteDatasources:
  - name: Prometheus
    orgId: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    uid: prometheus_uid
    url: http://diana-prometheus:9090
    basicAuth: false
    isDefault: true
    version: 1
    editable: false
    jsonData:
      httpMethod: POST
      prometheusType: Prometheus
      prometheusVersion: 2.47.0
      cacheLevel: 'High'
      disableMetricsLookup: false
      incrementalQuerying: true
      incrementalQueryOverlapWindow: 10m

  - name: Jaeger
    type: jaeger
    access: proxy
    orgId: 1
    uid: jaeger_uid
    url: http://diana-jaeger:16686
    basicAuth: false
    isDefault: false
    version: 1
    editable: false
    jsonData:
      tracesToLogs:
        datasourceUid: 'loki_uid'
        tags: ['job', 'instance', 'pod', 'namespace']
        mappedTags: [{'key': 'service.name', 'value': 'service'}]
        mapTagNamesEnabled: true
        spanStartTimeShift: '-1h'
        spanEndTimeShift: '1h'

  - name: PostgreSQL
    type: postgres
    access: proxy
    orgId: 1
    uid: postgres_uid
    url: diana-postgres:5432
    database: zmart_core
    user: zmart
    isDefault: false
    version: 1
    editable: false
    secureJsonData:
      password: zmart
    jsonData:
      sslmode: disable
      maxOpenConns: 100
      maxIdleConns: 100
      maxIdleConnsAuto: true
      connMaxLifetime: 14400
      postgresVersion: 1500
      timescaledb: false

  - name: Redis
    type: redis-datasource
    access: proxy
    orgId: 1
    uid: redis_uid
    url: redis://diana-redis:6379
    isDefault: false
    version: 1
    editable: false
    jsonData:
      client: standalone
      poolSize: 5
      timeout: 10
      pingInterval: 0