service_name: zmart-notification
service_type: backend
port: 8008
description: "ZmartBot notification and alerting service"
status: ACTIVE
passport_id: ZMBT-SRV-20250826-337DFE
registered_at: "2025-08-26"
health_url: "http://localhost:8008/health"
start_cmd: "python3 zmart_notification.py"
stop_cmd: "pkill -f 'zmart_notification.py'"
dependencies:
  - zmart-api
  - database
tags:
  - notification
  - alerting
  - backend
