service_name: pattern-recognition-service
service_type: backend
version: 1.0.0
owner: zmartbot
description: Pattern recognition service - needs ZMBT passport
port: 8096
passport_id: ZMBT-SRV-20250828-5E3119
status: ACTIVE
registered_at: '2025-08-31'
health_url: http://localhost:8096/health
start_cmd: python3 pattern_recognition_service_server.py --port 8096
stop_cmd: pkill -f 'pattern_recognition_service_server.py'
dependencies:
- zmart-api
tags:
- backend
- pattern-recognition-service
lifecycle:
  startup_grace_seconds: 30
  shutdown_timeout_seconds: 15
  health_check_interval: 30
monitoring:
  metrics_endpoint: /metrics
  logs_path: logs/pattern-recognition-service.log
  dashboard_url: http://localhost:8096/dashboard
security:
  cors_enabled: true
  token_required: false
  scopes:
  - backend
