service_name: scoring-service
service_type: backend
version: 1.0.0
owner: zmartbot
description: Scoring service - needs ZMBT passport
port: 8099
passport_id: ZMBT-SRV-20250828-0BFC67
status: ACTIVE
registered_at: '2025-08-31'
health_url: http://localhost:8099/health
start_cmd: python3 scoring_service_server.py --port 8099
stop_cmd: pkill -f 'scoring_service_server.py'
dependencies:
- zmart-api
tags:
- backend
- scoring-service
lifecycle:
  startup_grace_seconds: 30
  shutdown_timeout_seconds: 15
  health_check_interval: 30
monitoring:
  metrics_endpoint: /metrics
  logs_path: logs/scoring-service.log
  dashboard_url: http://localhost:8099/dashboard
security:
  cors_enabled: true
  token_required: false
  scopes:
  - backend
