service_name: market-data-service
service_type: backend
version: 1.0.0
owner: zmartbot
description: Market data service - needs ZMBT passport
port: 8095
passport_id: ZMBT-SRV-20250828-0F0DF4
status: ACTIVE
registered_at: '2025-08-31'
health_url: http://localhost:8095/health
start_cmd: python3 market_data_service_server.py --port 8095
stop_cmd: pkill -f 'market_data_service_server.py'
dependencies:
- zmart-api
tags:
- backend
- market-data-service
lifecycle:
  startup_grace_seconds: 30
  shutdown_timeout_seconds: 15
  health_check_interval: 30
monitoring:
  metrics_endpoint: /metrics
  logs_path: logs/market-data-service.log
  dashboard_url: http://localhost:8095/dashboard
security:
  cors_enabled: true
  token_required: false
  scopes:
  - backend
