# Type stubs for src modules (for test environment compatibility)
# This file provides type hints for cryptoverse src modules

from typing import Any, Optional, Dict, List
from datetime import datetime

# Database types
class CryptoverseDatabase:
    def __init__(self) -> None: ...
    def save_extraction_result(self, result: Any) -> bool: ...
    def get_latest_data(self, source: str, limit: int = 10) -> List[Dict[str, Any]]: ...

class DataExtractionResult:
    def __init__(
        self, 
        source: str, 
        timestamp: datetime, 
        data: Dict[str, Any], 
        success: bool = True,
        error_message: Optional[str] = None
    ) -> None: ...
    
    @property
    def source(self) -> str: ...
    @property
    def timestamp(self) -> datetime: ...
    @property
    def data(self) -> Dict[str, Any]: ...
    @property
    def success(self) -> bool: ...
    @property
    def error_message(self) -> Optional[str]: ...

# Extractor types
class CryptoRiskExtractor:
    def __init__(self, headless: bool = True) -> None: ...
    async def extract_crypto_risk_indicators(self) -> DataExtractionResult: ...
    async def extract_with_mock_data(self) -> DataExtractionResult: ...

class ScreenerExtractor:
    def __init__(self, headless: bool = True) -> None: ...
    async def extract_screener_data(self) -> DataExtractionResult: ...
    async def extract_with_mock_data(self) -> DataExtractionResult: ...